### ISSUE TITLE
Add new aliases and use same run commands as in zsh plugin

### ISSUE THREAD

**Issue by atomfrede** [jhipster/jhipster-fisherman-plugin#1]
See here: https://github.com/jhipster/jhipster-oh-my-zsh-plugin/commit/a95bc3f45af7d00cd88a5de6470132c0c2907c74#diff-722d7a2ca2fd9a123b9f0139ec47d541

**Comment by pascalgrimaud** [comment]
@atomfrede : I think it would be interesting if this plugin could share a common file with [jhipster.plugin.zsh](https://github.com/jhipster/jhipster-oh-my-zsh-plugin/blob/master/jhipster.plugin.zsh)
So we don't need to maintain 2 projects / 2 files

I don't know if it's doable.

**Comment by atomfrede** [comment]
Yes. Maybe we can try to make a common alias file, because many things are really identical
